// ==============================================================================
// MIT No Attribution
// 
// Copyright 2026 Thibault Fillion
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// ==============================================================================

#include <vector>
#include <iostream>
#include "numerics.hpp"
#include "physical_units.hpp"

struct TestCase{
	double v1;
	std::string u1;
	std::string u2;
	double v2;
	};
	
void test_convert(){
	std::cout<<"test_convert:"<<std::endl;
	
	// disclaimer:
	// test cases have been 
	// generated by a LLM.
	
	std::vector<TestCase> test_cases = {
		{1, "m", "nm", 1000000000},
		{1, "m", "pm", 1000000000000},
		{1, "m", "fm", 1000000000000000},
		{1, "mol", "nmol", 1000000000},
		{1, "mol", "pmol", 1000000000000},
		{1, "mol", "fmol", 1000000000000000},
		{1, "M", "nM", 1000000000},
		{1, "M", "pM", 1000000000000},
		{1, "M", "fM", 1000000000000000},
		{1, "s", "ns", 1000000000},
		{1, "s", "ps", 1000000000000},
		{1, "s", "fs", 1000000000000000},
		{1, "J", "nJ", 1000000000},
		{1, "J", "pJ", 1000000000000},
		{1, "J", "fJ", 1000000000000000},
		{1, "Pa", "nPa", 1000000000},
		{1, "Pa", "pPa", 1000000000000},
		{1, "Pa", "fPa", 1000000000000000},
		{1, "L", "nL", 1000000000},
		{1, "L", "pL", 1000000000000},
		{1, "L", "fL", 1000000000000000},
		{1, "N", "nN", 1000000000},
		{1, "N", "pN", 1000000000000},
		{1, "N", "fN", 1000000000000000},
		{1, "m/s", "nm/s", 1000000000},
		{1, "m/s", "pm/s", 1000000000000},
		{1, "m/s", "fm/s", 1000000000000000},
		{1, "m^2/s", "nm^2/s", 1000000000000000000},
		{1, "mol/L", "nmol/L", 1000000000},
		{1, "mol/L", "pmol/L", 1000000000000},
		{1, "mol/L", "fmol/L", 1000000000000000},
		{1, "J/mol", "nJ/mol", 1000000000},
		{1, "J/mol", "pJ/mol", 1000000000000},
		{1, "J/mol", "fJ/mol", 1000000000000000},
		{1, "fmol/s", "pmol/s", 0.001},
		{1, "pmol/s", "nmol/s", 0.001},
		{1, "nmol/s", "mmol/s", 0.000001},
		{1, "fmol/s", "fmol/min", 60},
		{1, "pmol/s", "pmol/h", 3600},
		{1, "nmol/min", "nmol/h", 60},
		{1, "pmol/L", "pM", 1},
		{1, "fmol/L", "fM", 1},
		{1, "nmol/L", "nM", 1},
		{1, "nmol/mL", "uM", 1},
		{1, "pmol/mL", "nM", 1},
		{1, "fmol/mL", "pM", 1},
		{1, "J/s", "W", 1},
		{1, "nJ/s", "nW", 1},
		{1, "pJ/s", "pW", 1},
		{1, "fJ/s", "fW", 1},
		{1, "N/m^2", "Pa", 1},
		{1, "nN/m^2", "nPa", 1},
		{1, "pN/m^2", "pPa", 1},
		{1, "fN/m^2", "fPa", 1},
		{1, "m", "cm", 100},
		{1, "m", "mm", 1000},
		{1, "km", "m", 1000},
		{1000, "J", "kJ", 1},
		{1, "kJ", "J", 1000},
		{1000, "Pa", "kPa", 1},
		{1, "kPa", "Pa", 1000},
		{1, "mol", "mmol", 1000},
		{1000, "mmol", "mol", 1},
		{1, "M", "mM", 1000},
		{1000000, "uM", "M", 1},
		{1, "L", "mL", 1000},
		{1000, "mL", "L", 1},
		{1000, "N", "kN", 1},
		{1, "min", "s", 60},
		{1, "h", "min", 60},
		{1, "h", "s", 3600},
		{1, "day", "h", 24},
		{1, "day", "s", 86400},
		{1, "m/s", "km/h", 3.6},
		{3.6, "km/h", "m/s", 1},
		{1, "m^2/s", "cm^2/s", 10000},
		{1, "m^2/s", "m^2/min", 60},
		{1, "m^2/s", "m^2/h", 3600},
		{1, "cm^2/s", "mm^2/s", 100},
		{1, "m/s^2", "m/min^2", 3600},
		{1000, "J/mol", "kJ/mol", 1},
		{1, "L/min", "L/h", 60},
		{1, "m^3/h", "L/h", 1000},
		{1, "K", "nK", 1000000000},
		{1, "K", "pK", 1000000000000},
		{1, "K", "fK", 1000000000000000},
		{1, "M/s", "M.s^-1", 1},
		{1, "M.s^-1", "M/s", 1},
		{1, "M/s", "M.s^-1", 1},
		{1, "M.s^-1", "M/s", 1},
		{1, "m/s", "m.s^-1", 1},
		{1, "m.s^-1", "m/s", 1},
		{1, "m/s^2", "m.s^-2", 1},
		{1, "m.s^-2", "m/s^2", 1},
		{1, "m^2/s", "m^2.s^-1", 1},
		{1, "J/mol", "J.mol^-1", 1},
		{1, "J.mol^-1", "J/mol", 1},
		{1, "mol/L", "mol.L^-1", 1},
		{1, "mol.L^-1", "mol/L", 1},
		{1, "N/m^2", "N.m^-2", 1},
		{1, "N.m^-2", "N/m^2", 1},
		{1, "m^2.s^-2", "m^2/s^2", 1},
		{1, "Pa.s", "kPa.s", 0.001},
		{1, "mol.L^-1.s^-1", "M/s", 1},
		{1, "M/s", "nmol.L^-1.s^-1", 1000000000},
		{1, "M / s", "M/s", 1},
		{1, "m   . s^-1", "m/ s", 1},
		{1, "J . mol^-1", "J/mol", 1},
		{1, "J/mol/s", "J.mol^-1.s^-1", 1},
		{1, "kJ/mol/s", "J/mol/s", 1000},
		{1, "M.m/s", "mM.m/ms", 1},
		{1, "Pa.m/s", "kPa.m/h", 3.6},
		{1, "J/mol/K", "mJ/mol/K", 1000},				
		{1, "J/mol/K/s", "J.mol^-1.K^-1.s^-1", 1},
		{1, "kJ/mol/K/s", "J/mol/K/s", 1000},
		{1, "J/mol/K/s", "J/mol/K/min", 60},
		{1, "M.m/s/s", "M.m.s^-2", 1},
		{1, "Pa.L/mol/K", "Pa.mL/mmol/K", 1},
		{1, "J.m/mol/K/s", "J.m.mol^-1.K^-1.s^-1", 1},
		{1, "kJ.m/mol/K/s", "J.m/mol/K/s", 1000},
		{1, "J.m/mol/K/s", "J.cm/mol/K/s", 100},
		{1, "J.m/mol/K/s", "J.m/mol/K/min", 60},
		{1, "Pa.m^3/mol/K/s", "Pa.L/mol/K/s", 1000}
		};
	
	std::vector<bool> results(test_cases.size());
	
	for(size_t i=0; i<test_cases.size(); i++){
		bool success = are_rel_close(convert(test_cases[i].v1, test_cases[i].u1, test_cases[i].u2), test_cases[i].v2);
		
		if(success){
			std::cout<<"case "<<i<<": success\n";
			}
		else{
			std::cout<<"case "<<i<<": fail\n";
			std::cout<<"==============="<<std::endl;
			std::cout<<"convert("<<
				test_cases[i].v1<<", "<<
				test_cases[i].u1<<", "<<
				test_cases[i].u2<<") == "<<
				test_cases[i].v2<<std::endl;
			std::cout<<"==============="<<std::endl;
			}
		}
	}

int main(){
	test_convert();
	return 0;
	}
